"$schema" = "schemas/schema.json"
[default]
description = """
This permission set configures which
share features are by default exposed.

#### Granted Permissions

It allows acccess to all share commands.

"""

permissions = [
  "allow-register-listener",
  "allow-remove-listener",
  "allow-share-text",
  "allow-share-file",
  "allow-get-pending-shared-content",
  "allow-clear-pending-shared-content",
]
